2021-07-05 17:24:11,157 ERROR: Exception on /search [GET] [in /home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/darkknight/microblog/app/main/routes.py", line 152, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/darkknight/microblog/app/models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/darkknight/microblog/app/search.py", line 22, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 1675, in search
    body=body,
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/transport.py", line 415, in perform_request
    raise e
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/transport.py", line 388, in perform_request
    timeout=timeout,
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 275, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 331, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2021-07-05 18:50:28,436 INFO: Microblog startup [in /home/darkknight/microblog/app/__init__.py:77]
2021-07-05 18:50:47,988 ERROR: Exception on /search [GET] [in /home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/darkknight/microblog/app/main/routes.py", line 153, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/darkknight/microblog/app/models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/darkknight/microblog/app/search.py", line 25, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 1675, in search
    body=body,
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/transport.py", line 415, in perform_request
    raise e
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/transport.py", line 388, in perform_request
    timeout=timeout,
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 275, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/darkknight/anaconda3/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 331, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2021-07-06 23:33:10,758 INFO: Microblog startup [in /home/darkknight/microblog/app/__init__.py:77]
2021-07-06 23:51:06,899 INFO: Microblog startup [in /home/darkknight/microblog/app/__init__.py:77]
2021-07-06 23:59:08,908 INFO: Microblog startup [in /home/darkknight/microblog/app/__init__.py:77]
2021-07-07 15:38:29,741 INFO: Microblog startup [in /home/darkknight/microblog/app/__init__.py:82]
2021-07-07 15:38:48,713 INFO: Microblog startup [in /home/darkknight/microblog/app/__init__.py:82]
2021-07-07 15:50:25,071 INFO: Microblog startup [in /home/darkknight/microblog/app/__init__.py:82]
2021-07-07 15:53:38,249 INFO: Microblog startup [in /home/darkknight/microblog/app/__init__.py:82]
2021-07-07 15:54:00,286 INFO: Microblog startup [in /home/darkknight/microblog/app/__init__.py:82]
2021-07-07 15:56:37,939 INFO: Microblog startup [in /home/darkknight/microblog/app/__init__.py:82]
